client_config_backend: settings
client_config:
  client_id: 774904283753-bnk8l7dpb3kh9v0asolvv4edauknbb56.apps.googleusercontent.com
  client_secret: fn4Z__lDJaiT3QLsDbZIL-sO

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True